-- Run this in Supabase SQL editor
CREATE TABLE IF NOT EXISTS banned_words (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  word        TEXT NOT NULL UNIQUE,
  replacement TEXT NOT NULL DEFAULT '',
  pattern_type TEXT NOT NULL DEFAULT 'other' CHECK (pattern_type IN ('verb','adjective','noun','phrase','other')),
  enabled     BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_banned_words_enabled ON banned_words (enabled);

-- Seed with current banned word list and their replacements
INSERT INTO banned_words (word, replacement, pattern_type) VALUES
  -- Verbs
  ('demonstrate',   'show',             'verb'),
  ('ensure',        'make sure',        'verb'),
  ('utilise',       'use',              'verb'),
  ('encompass',     'cover',            'verb'),
  ('facilitate',    'help',             'verb'),
  ('enhance',       'improve',          'verb'),
  ('maintain',      'keep',             'verb'),
  ('implement',     'carry out',        'verb'),
  ('foster',        'build',            'verb'),
  ('leverage',      'use',              'verb'),
  ('cultivate',     'build',            'verb'),
  ('streamline',    'simplify',         'verb'),
  ('liaise',        'work with',        'verb'),
  ('collaborate',   'work with',        'verb'),
  ('optimise',      'improve',          'verb'),
  ('mitigate',      'reduce',           'verb'),
  ('empower',       'support',          'verb'),
  ('uphold',        'follow',           'verb'),
  ('endeavour',     'try',              'verb'),
  ('aspire',        'aim',              'verb'),
  ('shape',         'influence',        'verb'),
  ('span',          'cover',            'verb'),
  ('reflect',       'show',             'verb'),
  ('delve',         'look into',        'verb'),
  ('unlock',        'open up',          'verb'),
  ('unveil',        'reveal',           'verb'),
  ('elevate',       'raise',            'verb'),
  ('nestle',        'sit',              'verb'),
  ('blend',         'combine',          'verb'),
  -- Adjectives / adverbs
  ('robust',        'strong',           'adjective'),
  ('holistic',      'wide-ranging',     'adjective'),
  ('comprehensive', 'thorough',         'adjective'),
  ('passionate',    'committed',        'adjective'),
  ('dedicated',     'committed',        'adjective'),
  ('hardworking',   'diligent',         'adjective'),
  ('grounded',      'practical',        'adjective'),
  ('seamlessly',    'smoothly',         'adjective'),
  ('crucial',       'key',              'adjective'),
  ('vital',         'key',              'adjective'),
  ('notably',       'in particular',    'adjective'),
  ('moreover',      'and also',         'adjective'),
  ('furthermore',   'and also',         'adjective'),
  ('additionally',  'and also',         'adjective'),
  ('proactive',     'forward-thinking', 'adjective'),
  ('dynamic',       'varied',           'adjective'),
  ('enthusiastic',  'keen',             'adjective'),
  ('compassionate', 'caring',           'adjective'),
  ('paramount',     'the priority',     'adjective'),
  ('pivotal',       'key',              'adjective'),
  ('integral',      'central',          'adjective'),
  ('imperative',    'essential',        'adjective'),
  ('adept',         'skilled',          'adjective'),
  ('multifaceted',  'varied',           'adjective'),
  ('nuanced',       'detailed',         'adjective'),
  ('bespoke',       'tailored',         'adjective'),
  ('tremendously',  'greatly',          'adjective'),
  ('immensely',     'greatly',          'adjective'),
  ('substantially', 'considerably',     'adjective'),
  ('bustling',      'busy',             'adjective'),
  ('vibrant',       'lively',           'adjective'),
  ('daunting',      'challenging',      'adjective'),
  ('overarching',   'overall',          'adjective'),
  ('impactful',     'effective',        'adjective'),
  ('transformative','significant',      'adjective'),
  ('synergy',       'joint working',    'adjective'),
  -- Nouns
  ('plethora',      'range',            'noun'),
  ('realm',         'area',             'noun'),
  ('tapestry',      'mix',              'noun'),
  ('landscape',     'setting',          'noun'),
  -- Phrases
  ('highly motivated',         'driven',               'phrase'),
  ('central to',               'key to',               'phrase'),
  ('at all times',             'always',               'phrase'),
  ('in order to',              'to',                   'phrase'),
  ('with regard to',           'about',                'phrase'),
  ('in relation to',           'about',                'phrase'),
  ('due to the fact that',     'because',              'phrase'),
  ('going forward',            'in future',            'phrase'),
  ('moving forward',           'in future',            'phrase'),
  ('touch base',               'catch up',             'phrase'),
  ('not only',                 'and',                  'phrase'),
  ('not just',                 '',                     'phrase'),
  ('more than just',           '',                     'phrase'),
  ('significantly improved',   'improved',             'phrase'),
  ('greatly improved',         'improved',             'phrase'),
  ('substantially improved',   'improved',             'phrase'),
  ('proven track record',      'strong history of',    'phrase'),
  ('fast-paced environment',   'busy environment',     'phrase'),
  ('attention to detail',      'careful work',         'phrase'),
  ('team player',              'works well with others','phrase'),
  ('think outside the box',    'find new approaches',  'phrase'),
  ('results-driven',           'outcome-focused',      'phrase'),
  ('go above and beyond',      'put in extra effort',  'phrase'),
  ('invaluable experience',    'strong experience',    'phrase'),
  ('from day one',             'from the start',       'phrase'),
  ('from the first shift',     'from the start',       'phrase'),
  ('This resulted in',         'which meant',          'phrase'),
  ('This led to',              'which meant',          'phrase'),
  ('As a result',              'So',                   'phrase'),
  ('I would bring',            'I bring',              'phrase'),
  ('I would ensure',           'I make sure',          'phrase'),
  ('I would contribute',       'I contribute',         'phrase'),
  ('I would strive',           'I aim',                'phrase'),
  ('I believe I would',        'I will',               'phrase'),
  ('I am confident that',      '',                     'phrase'),
  ('I am deeply committed',    'I am committed',       'phrase'),
  ('I genuinely believe',      'I believe',            'phrase'),
  ('I truly care',             'I care',               'phrase')
ON CONFLICT (word) DO NOTHING;
