-- Paragraph Openers table — run once in your Supabase SQL editor
-- Creates the table and seeds it with the default 100 openers (50 per set).

CREATE TABLE IF NOT EXISTS paragraph_openers (
  id          SERIAL PRIMARY KEY,
  set_number  INTEGER NOT NULL CHECK (set_number IN (1, 2)),
  position    INTEGER NOT NULL,
  text        TEXT NOT NULL,
  enabled     BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (set_number, position)
);

-- Seed Set 1 (50 openers)
INSERT INTO paragraph_openers (set_number, position, text) VALUES
(1,  1,  'Over the years, I have learned that…'),
(1,  2,  'In my experience, the most important part of this role is…'),
(1,  3,  'Working on the ward has shown me that…'),
(1,  4,  'Every shift reminds me of the importance of…'),
(1,  5,  'One thing I have always valued in this job is…'),
(1,  6,  'I approach my work with…'),
(1,  7,  'Throughout my career, I have consistently made a point of…'),
(1,  8,  'Looking back, I can say with confidence that…'),
(1,  9,  'From my first shift to now, I have understood that…'),
(1, 10,  'Day to day patient care has taught me…'),
(1, 11,  'Quality care, in my experience, starts with…'),
(1, 12,  'I have seen firsthand how much it matters to…'),
(1, 13,  'My experience has given me a clear understanding of…'),
(1, 14,  'Caring for patients has always meant…'),
(1, 15,  'I believe small actions often make the biggest difference.'),
(1, 16,  'I have built my skills over time through…'),
(1, 17,  'One lesson I carry with me is…'),
(1, 18,  'I take pride in…'),
(1, 19,  'Supporting patients has helped me develop…'),
(1, 20,  'Being part of a busy team has taught me…'),
(1, 21,  'No two shifts are the same, and that has taught me…'),
(1, 22,  'I understand the responsibility that comes with…'),
(1, 23,  'Over time, I have grown confident in…'),
(1, 24,  'I have learned the value of working closely with others.'),
(1, 25,  'I know from experience that…'),
(1, 26,  'A caring approach has always guided my work.'),
(1, 27,  'I want patients to feel they can rely on me.'),
(1, 28,  'I believe compassion is central to good care.'),
(1, 29,  'My role has required me to…'),
(1, 30,  'I have come to understand the importance of…'),
(1, 31,  'Working well with others is something I take seriously.'),
(1, 32,  'I see teamwork as essential to good patient care.'),
(1, 33,  'I have worked in settings where…'),
(1, 34,  'I stay focused on providing safe, effective care.'),
(1, 35,  'Clear communication has always been one of my strengths.'),
(1, 36,  'I have learned to stay steady under pressure.'),
(1, 37,  'I understand what it means to prioritise patient needs.'),
(1, 38,  'Accuracy and attention to detail matter to me.'),
(1, 39,  'I stay open to learning and adapting.'),
(1, 40,  'I enjoy contributing to a positive, supportive team.'),
(1, 41,  'My experience has prepared me to…'),
(1, 42,  'I take a practical, patient-centred approach to…'),
(1, 43,  'Dignity and respect guide how I treat every patient.'),
(1, 44,  'Building trust with patients has always come naturally to me.'),
(1, 45,  'I am comfortable working independently and as part of a team.'),
(1, 46,  'I believe every patient deserves…'),
(1, 47,  'Offering reassurance is something I take seriously.'),
(1, 48,  'I bring professionalism and compassion to every shift.'),
(1, 49,  'I have developed strong skills in…'),
(1, 50,  'These experiences have shaped how I approach patient care today.'),

-- Seed Set 2 (50 openers)
(2,  1,  'In this role, I have gained solid experience in…'),
(2,  2,  'Through my day-to-day work, I have become confident in…'),
(2,  3,  'Over time, I have developed a good understanding of…'),
(2,  4,  'I have had plenty of opportunities to…'),
(2,  5,  'Working with different patients has helped me…'),
(2,  6,  'One area I have become particularly confident in is…'),
(2,  7,  'A big part of my role has involved…'),
(2,  8,  'I regularly work alongside…'),
(2,  9,  'This has allowed me to build experience in…'),
(2, 10,  'I have learned how important it is to…'),
(2, 11,  'From my experience, good care depends on…'),
(2, 12,  'I always try to make sure…'),
(2, 13,  'I understand the importance of…'),
(2, 14,  'In my daily work, I make a point of…'),
(2, 15,  'I am used to working in…'),
(2, 16,  'I have become comfortable with…'),
(2, 17,  'I have worked with patients who…'),
(2, 18,  'My experience has helped me develop…'),
(2, 19,  'I understand what is expected when…'),
(2, 20,  'I have always approached my work by…'),
(2, 21,  'I have found that clear communication helps…'),
(2, 22,  'In a busy healthcare setting, I have learned to…'),
(2, 23,  'I am confident when it comes to…'),
(2, 24,  'I take care to ensure…'),
(2, 25,  'I work closely with colleagues to…'),
(2, 26,  'I know how important it is to…'),
(2, 27,  'I have experience supporting patients with…'),
(2, 28,  'I am familiar with…'),
(2, 29,  'I have developed good working relationships with…'),
(2, 30,  'I enjoy working as part of a team because…'),
(2, 31,  'I understand that patients often need…'),
(2, 32,  'I have seen how small actions can make a difference.'),
(2, 33,  'I always remain mindful of…'),
(2, 34,  'I have built my confidence through…'),
(2, 35,  'I am comfortable prioritising my workload when…'),
(2, 36,  'I have experience completing…'),
(2, 37,  'I make sure I communicate clearly with…'),
(2, 38,  'I understand the need to follow…'),
(2, 39,  'I have worked in situations where…'),
(2, 40,  'I take a practical approach to…'),
(2, 41,  'I have supported colleagues by…'),
(2, 42,  'I have experience balancing…'),
(2, 43,  'I have become more confident in managing…'),
(2, 44,  'I always try to provide…'),
(2, 45,  'I understand the value of treating everyone with…'),
(2, 46,  'I have developed a calm approach to…'),
(2, 47,  'I am committed to maintaining…'),
(2, 48,  'I take pride in being reliable and…'),
(2, 49,  'My experience has given me the confidence to…'),
(2, 50,  'This experience has prepared me well for…')
ON CONFLICT (set_number, position) DO NOTHING;
