import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'
import { verifyAdminToken } from '@/lib/auth'

function generateCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
  let c = 'NHS'
  for (let i = 0; i < 5; i++) c += chars[Math.floor(Math.random() * chars.length)]
  return c
}

const candidates = [
  { full_name: 'Angela', work_history: 'Current: Altogether Care – Healthcare Assistant\nPrevious: Victory Specialist Hospital', qualifications: 'BSc International Business Economics, Masters Degree in Health and Care, SVQ/NVQ Mental Health, GCSE Mathematics, GCSE English Language\nAutism eLearning, Basic Life Support, Care Certificate, COSHH, Dementia Awareness, Equality & Diversity, Infection Prevention & Control, Medication Administration, Moving and Assisting People, Safeguarding Adults', skills: 'Person Centred Software, eMAR, Care Vision, Microsoft Office Suite', background: 'Driving: Full UK Driving License. Focus on healthcare experience from current and previous roles.' },
  { full_name: 'Bolu', work_history: 'Current: Aaron Gregory – SEN Support/Teaching Assistant\nPrevious: Victory Specialist Hospital', qualifications: 'Masters Strategic Project Management, BSc Psychology', skills: 'School Management Information Systems, Microsoft Office Suite, Educational databases', background: 'Driving: Not specified. Non-healthcare current role. TRANSFERABLE SKILLS: Educational support, communication with children and families, patience, adaptability.' },
  { full_name: 'Ogene', work_history: 'Current: Cuerden Care Horwich Bolton – Support Worker\nPrevious: Victory Specialist Hospital', qualifications: 'MSc International Business with Human Resources Management, BSc Microbiology, GCSE English, GCSE Mathematics\nLevel 3 Diploma in Health and Social Care, Care Certificate, CSTF Health Safety and Welfare, CSTF Equality Diversity and Human Rights, CSTF Infection Prevention & Control, CSTF Moving & Handling, CSTF Resuscitation Adults, CSTF NHS Conflict Resolution, CSTF Safeguarding Adults and Children', skills: 'Care Vision, Log my Care, Microsoft Office Suite', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Shinaayomi', work_history: 'Current: Eden Futures Newark – Healthcare Support Worker\nPrevious: General Hospital Ado-Ekiti Nigeria', qualifications: 'Bachelor of Education B.Ed Political Science Second Class Honours, GCSE English Grade B, GCSE Mathematics Grade B\nNVQ Level 3 Diploma in Health and Social Care, National Care Certificate, Infection Control, Health and Safety, Level 3 Safeguarding Adults and Children, Moving and Handling, Mental Capacity Act, Prevention and Management of Violence and Aggression', skills: 'Microsoft Office Suite, Electronic healthcare record systems, Hospital information systems', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Faderera', work_history: 'Current: Tezlom Healthcare Staffing Agency – Healthcare Support Worker\nPrevious: Victory Specialist Hospital', qualifications: 'Bachelor Agriculture, Horticulture', skills: 'Care agency scheduling software, Mobile handover apps, Microsoft Office Suite', background: 'Driving: Not specified. Focus on healthcare experience.' },
  { full_name: 'Amusu', work_history: 'Current: Ison Nursing & Care Services Ltd – Senior Healthcare Support Worker\nPrevious: Sacred Heart Hospital', qualifications: 'Not specified', skills: 'Care Vision, Log my Care, Electronic daily notes systems, Microsoft Office Suite', background: 'Driving: Not specified. Focus on healthcare experience.' },
  { full_name: 'Gbemi', work_history: 'Current: The Bells Academy Health Care – Healthcare Assistant\nPrevious: Victory Specialist Hospital', qualifications: 'LL.B 2nd Class Lower', skills: 'Person Centred Software, Birdie, eMAR, Microsoft Office Suite', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Toife', work_history: 'Current: Glenholme – Healthcare Support Worker\nPrevious: Victory Specialist Hospital', qualifications: 'BSc Political Science', skills: 'Care Vision, Person Centred Software, eMAR, Microsoft Office Suite', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Bosei', work_history: 'Current: Frenchay Brain Injury Rehabilitation Center – Rehabilitation Assistant\nPrevious: Victory Specialist Hospital', qualifications: 'Banking & Finance, Business Studies', skills: 'Specialist rehabilitation software, Electronic patient records, Microsoft Office Suite', background: 'Driving: Not specified. Focus on healthcare experience.' },
  { full_name: 'Betty', work_history: 'Current: DNA Recruitment Agency – Healthcare Support Worker\nPrevious: Faith Foundation Hospital', qualifications: 'MSc International Business, BSc Sociology', skills: 'Care agency scheduling software, Mobile handover apps, Microsoft Office Suite', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Beelz', work_history: 'Current: Reach Volunteering – Voluntary Data Manager\nPrevious: Topside Care Home', qualifications: 'BSc Banking & Finance, Data Analytics & Mentorship, Data Analysis', skills: 'Database management systems, Microsoft Office Suite Excel Access, Data visualization tools', background: 'Driving: Not specified. Non-healthcare current role. TRANSFERABLE SKILLS: Database management, data organization, attention to detail.' },
  { full_name: 'Motun Filani', work_history: 'Current: Destiny Healthcare Provider – Healthcare Support Worker\nPrevious: Victory Specialist Hospital', qualifications: 'BSc Sociology, Certificate Computer Appreciation, Diploma Social Development', skills: 'Care Vision, Log my Care, Microsoft Office Suite', background: 'Driving: Driver. Focus on healthcare experience.' },
  { full_name: 'Femi', work_history: 'Current: Hybrid Group – Healthcare Support Worker\nPrevious: Victory Specialist Hospital', qualifications: 'Cell Biology & Genetics', skills: 'Care Vision, Mobile Care Monitoring, Microsoft Office Suite', background: 'Driving: Not specified. Focus on healthcare experience.' },
  { full_name: 'Olatoye', work_history: 'Current: Easehealthcare Group – Healthcare Support Worker\nPrevious: Victory Specialist Hospital', qualifications: 'BSc Industrial Relations & Personnel Management', skills: 'Care Vision, Log my Care, Microsoft Office Suite', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Jubilee', work_history: 'Current: Longley Park View-Exemplar Home – Healthcare Assistant\nPrevious: Victory Specialist Hospital', qualifications: 'B.Tech Manufacturing Engineering, HND Civil Engineering', skills: 'Person Centred Software, eMAR, Care home management systems, Microsoft Office Suite', background: 'Driving: Full UK Driving License. Focus on healthcare experience.' },
  { full_name: 'Kazeem Amusa', work_history: 'Current: Last Minute Care & Nursing – Healthcare Support Worker Band 3\nPrevious: Victory Specialist Hospital', qualifications: 'MSc Project Management, BSc/B.Ed Economics Education', skills: 'Care Vision, Log my Care, Mobile Care Monitoring, Microsoft Office Suite', background: 'Driving: Driver B BE C. Focus on healthcare experience.' },
  { full_name: 'Mathew', work_history: 'Current: Job and Talent – Warehouse Operator\nPrevious: Victory Specialist Hospital', qualifications: 'HND, NABTEB', skills: 'Warehouse Management Systems, Microsoft Office Suite', background: 'Driving: Non-driver. Non-healthcare current role. Previous healthcare experience should be emphasized.' },
  { full_name: 'Shakirat', work_history: 'Current: Ivolve Care Ltd – Support Worker\nPrevious: JIWA Healthcare Facility', qualifications: 'Masters Public Relations, Bachelor of Education', skills: 'Care Vision, Log my Care, Person Centred Software, Microsoft Office Suite', background: 'Driving: Driver. Focus on healthcare experience.' },
  { full_name: 'Udeh Onyinye Precious', work_history: 'Current: NHS Professionals – Healthcare Assistant\nPrevious: Manchester Royal Infirmary', qualifications: 'MSc Adult Nursing, MSc Public Administration HRM, BSc Public Administration', skills: 'PAS Patient Administration System, SystmOne/Lorenzo, Datix, NHS Professionals booking system, Microsoft Office Suite', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Abass', work_history: 'Current: Avon and Wiltshire NHS Trust – Hotel Services Assistant\nPrevious: Faith Foundation Hospital', qualifications: 'MA International Politics, BSc Political Science, GCSE English equivalent, GCSE Mathematics equivalent\nLevel 3 Diploma in Health and Social Care, Care Certificate, Basic Life Support, Safeguarding Adults, Medication Administration, Oliver McGowan Training, Phlebotomy, Cognitive Behavioural Therapy', skills: 'NHS Trust internal systems, Facilities management software, Microsoft Office Suite', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Halfan', work_history: 'Current: Avon Healthcare Solutions Ltd – Healthcare Support Worker\nPrevious: Victory Specialist Hospital', qualifications: 'BBA', skills: 'Care Vision, Log my Care, Microsoft Office Suite', background: 'Driving: Not specified. Focus on healthcare experience.' },
  { full_name: 'Leo Kariuki', work_history: 'Current: Tiny Rebel Brewery and Restaurant Newport – Line Chef\nPrevious: Caffi Crane Food and Chips Newport', qualifications: 'Vocational Studies ICT and Business Diploma, GCSE English equivalent\nFood Hygiene and Safety Level 3, Health and Social Care Level 3, Mental Health Diploma, Caregiving Diploma', skills: 'Restaurant POS systems, Stock management software, Microsoft Office Suite', background: 'Driving: Not specified. Non-healthcare current role. TRANSFERABLE SKILLS: Working under pressure, time management, hygiene standards, team coordination.' },
  { full_name: 'Sekinat', work_history: 'Current: Swifthand Care Services Limited – Healthcare Assistant\nPrevious: Victory Specialist Hospital', qualifications: 'Masters Degree in Environmental Toxicology First Class Honours, Bachelor Degree in Environmental Management and Toxicology, GCSE Mathematics and English Grade B\nNVQ Level 3 Diploma in Adult Care, Care Certificate, Wound Care, Phlebotomy, Tracheostomy Care, Continence and Catheter Care, PEG and JEJ Feeding Care', skills: 'Care Vision, Log my Care, Electronic care record systems, Mobile Care Monitoring, Microsoft Office Suite', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Asmau', work_history: 'Current: Curragate Care – Healthcare Support Worker; Sheffield NHS Trust – Support Worker Volunteer\nPrevious: Victory Hospital', qualifications: 'NVQ Level 3 in Health and Social Care, Safe Handling of Medication, Safeguarding & Mental Capacity Act Training, Care Certificate Standards, Learning Disability and Autism Training, CSTF Mandatory Training, Deprivation of Liberty Safeguards', skills: 'Care Vision, Person Centred Software, NHS volunteer systems, Microsoft Office Suite', background: 'Driving: Full UK Driving License. Focus on healthcare experience.' },
  { full_name: 'Sharon', work_history: 'Current: Castel Froma Neuro Care – Health Care Assistant Grade 3\nPrevious: Victory Specialist Hospital', qualifications: 'BA French Language, QualiS Level 3 Diploma in Health and Social Care, Care Certificate Diploma\nNVQ 3 in Health and Social Care, Moving & Handling, Tracheostomy Care, Stoma Care, Infection Control, BLS, End of Life Care, Mental Capacity, Safeguarding Adults, Autism & Learning Disability Awareness', skills: 'Person Centred Software, eMAR, Specialist neuro care systems, Microsoft Office Suite', background: 'Driving: Non-driver. Residents Choice Award - Carer of the Month. Focus on healthcare experience.' },
  { full_name: 'Lateef', work_history: 'Current: The Sibelco Group – Industrial Cleaner\nPrevious: Victory Hospital', qualifications: 'MSc Financial Management, BTech Urban and Regional Planning, GCSE equivalent\nNational Care Certificate, Level 3 Diploma in Health and Social Care, SIA Door Supervisor', skills: 'Facilities management systems, Microsoft Office Suite', background: 'Driving: Non-driver. Non-healthcare current role. TRANSFERABLE SKILLS: Hygiene and safety standards, following protocols, attention to detail.' },
  { full_name: 'Abigail', work_history: 'Current: Druid Stoke Care Home – Healthcare Assistant\nPrevious: Effiduase District Specialist Hospital', qualifications: 'National Diploma in Nursing, Registered Nurse with UK NMC Pin, GCSE English equivalent, GCSE Mathematics equivalent', skills: 'Person Centred Software, eMAR, Care home management systems, Microsoft Office Suite', background: 'Driving: Non-driver. Registered Nurse NMC Pin holder. Care home role - avoid critical nursing duties in statements.' },
  { full_name: 'Bidemi', work_history: 'Current: Victory Specialist Hospital Bayelsa Nigeria – Nursing Assistant\nPrevious: Faith Foundation Hospital Bayelsa Nigeria', qualifications: 'Level 3 Diploma in Health and Social Care, Care Certificate, BSc Pure and Applied Chemistry, GCSE\nSafeguarding Adults, Basic Life Support, Moving & Handling, Infection Prevention Control, Mental Capacity, Medication Administration, GDPR', skills: 'NHIMS Nigeria Health Information Management System, OpenMRS, Hospital Management System, Microsoft Office Suite', background: 'Driving: Non-driver. Focus on healthcare experience.' },
  { full_name: 'Derick', work_history: 'Current: Afeni Healthcare Limited – Team Leader Support Worker Band 3\nPrevious: Victory Specialist Hospital', qualifications: 'Bachelor of Science Petroleum Engineering, Advanced-level Chemistry Biology Physics Mathematics French, GCSE English equivalent, GCSE Mathematics equivalent\nNVQ Level 3 Diploma in Adult Care, Care Certificate, Oliver McGowan Training, Mental Health First Aid, Positive Behaviour Support, Epilepsy Awareness, Safeguarding Adults and Children, Infection Prevention and Control, Medication Administration, GDPR, Deprivation of Liberty Safeguards, Moving and Handling, Dementia, Mental Capacity', skills: 'Care Vision, Log my Care, Person Centred Software, Microsoft Office Suite', background: 'Driving: Full UK Driving License. Extensive training portfolio. Focus on healthcare experience.' },
  { full_name: 'Fisope', work_history: 'Current: Royalpeace Care – Senior Healthcare Assistant Grade 3\nPrevious: Victory Specialist Hospital', qualifications: 'NCE, Bachelor Degree in Biology Education Second Class Lower, GCSE English equivalent, GCSE Mathematics equivalent\nNVQ Level 3, Care Certificate, Medication Administration, Epilepsy Awareness, Nutrition and Hydration, MCA Competency, Mental Health Awareness, Infection Prevention and Control, End of Life Care, Dementia Awareness, Basic Life Support, Autism Understanding', skills: 'Care Vision, Person Centred Software, eMAR, Log my Care, Microsoft Office Suite', background: 'Driving: Full UK Driving License. Focus on healthcare experience.' },
  { full_name: 'Joke', work_history: 'Current: North Bristol NHS Trust Southmead Hospital – Health Care Support Worker Band 3\nPrevious: Tosin Medical Centre', qualifications: 'Higher National Diploma in Banking and Finance, SSCE\nNHS Care Certificate, Safeguarding Children Level 2-3, Oliver McGowan Training, Infection Prevention and Control, Conflict Resolution, Health and Safety, Resuscitation', skills: 'PAS Patient Administration System, SystmOne/Lorenzo, Datix, Electronic Prescribing System, Ward management systems, Microsoft Office Suite', background: 'Driving: Full UK Driving License. NHS staff at North Bristol NHS Trust Southmead Hospital.' },
  { full_name: 'Fuad', work_history: 'Current: Sheffield Childrens NHS Foundation Trust – Nursing Support Worker Band 3\nPrevious: Faith Foundation Hospital', qualifications: 'MSc Financial Management, Level 3 Diploma in Health and Social Care, GCSE Mathematics, GCSE English Grade B\nOliver McGowan Mandatory Training, Safeguarding Adults Level 1 and 2, Dementia Awareness, Basic Life Support, Medication Administration, Conflict Resolution, Moving and Handling, Epilepsy Awareness, Equality Diversity and LGBTQ, Fluids and Nutrition, Food Hygiene', skills: 'PAS Patient Administration System, SystmOne/Lorenzo, Datix, Electronic Prescribing System, Ward management systems, Microsoft Office Suite', background: 'Driving: Non-driver. NHS staff at Sheffield Childrens NHS Foundation Trust.' },
  { full_name: 'Mona', work_history: 'Current: Xero UK – Customer Experience Specialist (non-healthcare)\nPrevious healthcare: Allied Healthcare Care Assistant Nov 2022 - May 2023, Dominion Clinic Care Assistant Jan 2021 - Apr 2022, Victory Specialist Hospital', qualifications: 'MSc Business Analytics Merit, BSc Accounting, Level 3 Diploma in Health and Social Care, UK Care Certificate, GCSE Maths and English\nIntroduction to Health and Safety & COSHH, Equality & Diversity, Working In A Person-Centered Way, Understanding Autism, Positive Behaviour Support, Dementia Awareness', skills: 'Microsoft Office Suite Excel PowerPoint Word, Power BI, Database management systems, Electronic care record systems', background: 'Driving: Non-driver. PREVIOUS HEALTHCARE: Allied Healthcare Care Assistant, Dominion Clinic Care Assistant. MENTAL HEALTH EXPERTISE: acute psychiatric settings, MHA/MCA/DoLS, recovery models, risk assessments, care planning, vital signs, catheter care, BLS/CPR.' },
  { full_name: 'Victor', work_history: 'Current: MyHarmony Care – Healthcare Support Worker Grade 3\nPrevious: Care UK Healthcare Assistant June-Nov 2025 Cardiff, Victory Specialist Hospital Senior Theatre Support Worker Jan 2022 - Aug 2023 Nigeria', qualifications: 'Project Management University of South Wales, BSc Public Administration Second Class Honours, GCSE English equivalent, GCSE Mathematics equivalent\nNVQ Level 3 Diploma in Health and Social Care, National Care Certificate, Level 2 Manual Handling, Fire Safety, Safeguarding Children and Adults, Oliver McGowan Mandatory Training', skills: 'Care Vision, Log my Care, Person Centred Software, Microsoft Office Suite, Care planning software', background: 'Driving: Full UK Driving License plus Car. UNIQUE SKILLS: Theatre/surgical support experience, Project Management qualification.' },
  { full_name: 'Dora', work_history: 'Current: ACE Healthcare Ltd Bristol – Healthcare Support Worker Grade 3\nPrevious: Faith Foundation Hospital Ghana Support Worker Oct 2017 - Mar 2023 over 5 years', qualifications: 'Higher National Diploma HND Fashion Design and Technology Merit, GCSE Mathematics equivalent, GCSE English equivalent\nNVQ Level 3 Diploma in Health and Social Care, National Care Certificate, Positive Behaviour Management 1 and 2, Phlebotomy Venepuncture and Cannulation, Tracheostomy Management and PEG Feeding, Dysphagia Care, Adult and Paediatric Basic Advanced Life Support, Paediatric Advanced Life Support, Advanced Cardiac Life Support', skills: 'Care Vision, Log my Care, Electronic care record systems, Microsoft Office Suite', background: 'Driving: Non-driver. SPECIALIST CLINICAL SKILLS: Phlebotomy Venepuncture & Cannulation, Tracheostomy management, PEG feeding, Dysphagia care, Advanced Life Support Adult & Paediatric, Advanced Cardiac Life Support.' },
  { full_name: 'Lewa', work_history: 'Current: NHS Highland Trust New Craigs Hospital Inverness – Healthcare Support Worker Grade 3\nPrevious: Federal Teaching Hospital Nigeria Senior Nursing Officer Sept 2018 - Dec 2023, Archway Respite and Housing Aberdeen, Linn Moor Residential School VSA Aberdeen', qualifications: 'Bachelor of Science BSc Nursing 2.1 Honours, GCSE Mathematics equivalent Grade C, GCSE English equivalent Grade C\nCare Certificate NHS Highland, Adult Protection Certification, Venepuncture/Phlebotomy, Medication Administration, Positive Behavioural Support, Moving and Handling, Basic Life Support and Resuscitation, Infection Control, Adult and Child Protection, Management of Epilepsy', skills: 'TrakCare, MORSE, North of Scotland NoS Care Portal, NHIMS Nigeria, Microsoft Office Suite', background: 'Driving: Non-driver. NHS SCOTLAND STAFF at NHS Highland Trust New Craigs Hospital Inverness. SSSC REGISTERED Reg 4115855 Renewal 30/06/2029. BSc NURSING 2.1 Honours. SPECIALIST SKILLS: Venepuncture/Phlebotomy, Positive Behavioural Support, Epilepsy Management.' },
  { full_name: 'Prince', work_history: 'Current: Opus Healthcare Service Ltd – Healthcare Assistant Grade 3 Sept 2023 to Present\nPrevious: Angelic Care Specialist Hospital and Maternity Nigeria Senior Healthcare Support Worker Jan 2019 - Sept 2023', qualifications: 'BSc Geography and Planning Second Class Honours, GCSE Mathematics equivalent, GCSE English equivalent\nPMVA Prevention and Management of Violence and Aggression, National Care Certificate, Level 3 Diploma in Health and Social Care, Venepuncture and Cannulation, Blood Transfusion Training, Tracheostomy Management, ECG Recording and Interpretation, MCA and DoLS, NEWS2 and Vital Signs Monitoring, Basic Life Support and AED, Personality Disorder Awareness, Substance Misuse and Dual Diagnosis Support, De-escalation Skills, Infection Prevention and Control Level 2, GDPR', skills: 'Electronic care record systems, NHIMS Nigeria, OpenMRS, Microsoft Office Suite', background: 'Driving: Non-driver. SPECIALIST CLINICAL SKILLS: Venepuncture and Cannulation, Tracheostomy Management, ECG Recording, Blood Transfusion. MENTAL HEALTH EXPERTISE: PMVA, MCA/DoLS, Personality Disorder Awareness, Substance Misuse, De-escalation.' },
  { full_name: 'Nkem', work_history: 'Current: Care Connect Bury Ltd – Healthcare Support Worker Grade 3 Feb 2026 to Present\nPrevious: DMD Partners Healthcare Support Worker Dec 2022 - Jan 2026, Federal Medical Centre Abia State Nigeria Senior Activity Coordinator March 2016 - Oct 2022', qualifications: 'Banking and Finance Second Class Abia State University, GCSE Mathematics Grade A, GCSE English Grade A\nNVQ Level 3 Health and Social Care Diploma, Care Certificate, Mental Health Awareness and Legislation Level 3, Learning Disabilities Awareness, Autism Awareness Oliver McGowan, Conflict Management, Epilepsy Awareness, Safety Intervention, Medication Training Level 2, Manual Handling, Basic Life Support Adult and Paediatric, Infection Prevention and Control Level 1 and 2, GDPR', skills: 'Electronic care record systems, Care Apps, Hospital Management System, Microsoft Office Suite', background: 'Driving: Full UK Driving License. LEARNING DISABILITIES & AUTISM EXPERTISE: Extensive experience supporting individuals with learning disabilities, autism, challenging behaviours. Makaton, PECS, visual aids. MENTAL HEALTH BACKGROUND: Therapeutic activity programmes for inpatients at Federal Medical Centre 6+ years. MDT collaboration, care planning, risk assessment.' },
  { full_name: 'Ridah', work_history: 'Current: Sirona Care & Health CIC NHS – Healthcare Support Worker Band 3\nPrevious: Victory Hospital', qualifications: 'Certificate in Medical Laboratory Chemequip Medical Laboratory School, GCSE Mathematics equivalent, GCSE English equivalent\nNational Care Certificate, Level 3 Diploma in Health and Social Care, Laboratory Safety and Infection Prevention, HIV/AIDS Awareness and Counseling, First Aid and CPR, Integrated Management of Childhood Illness IMCI, Cancer Awareness', skills: 'Electronic care record systems, NHS IT systems, Microsoft Office Suite, Laboratory information systems', background: 'Driving: Non-driver. NHS STAFF at Sirona Care & Health CIC NHS Band 3. SPECIALIST BACKGROUND: Medical Laboratory Certificate, Laboratory Safety. ADDITIONAL: HIV/AIDS Awareness and Counseling, IMCI, Cancer Awareness.' },
]

export async function GET(req: NextRequest) {
  if (!verifyAdminToken(req)) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const end = new Date('2099-12-31').toISOString()
  const results = []
  const errors = []

  for (const c of candidates) {
    const client_code = generateCode()
    const { data, error } = await supabaseAdmin
      .from('clients')
      .insert({
        client_code,
        full_name: c.full_name,
        work_history: c.work_history,
        qualifications: c.qualifications,
        skills: c.skills,
        background: c.background,
        subscription_start: new Date().toISOString(),
        subscription_end: end,
        is_active: true,
      })
      .select()
      .single()

    if (error) {
      errors.push({ name: c.full_name, error: error.message })
    } else {
      results.push({ name: data.full_name, code: data.client_code })
    }
  }

  return NextResponse.json({ imported: results.length, results, errors })
}
