export interface BannedWordHit {
  word: string     // canonical form, e.g. "shape"
  found: string    // actual token matched, e.g. "shapes"
  sentence: string // full sentence containing the hit
}

interface BannedPattern {
  pattern: RegExp
  word: string
}

// Fixed opener sentences generated by the prompt templates that legitimately
// contain banned words — exempt these exact sentences from the scan.
const OPENER_EXEMPT: RegExp[] = [
  // England/Wales opening style 5: "...has shaped every aspect of my professional development"
  /has shaped every aspect/i,
  // England/Wales opening style 14: "...has shaped how I understand"
  /has shaped how I understand/i,
  // England/Wales opening style 15: "That moment reflects the care I bring"
  /That moment reflects the care/i,
  // Scotland Q2 values opener: "have been shaped by values that mirror"
  /have been shaped by values/i,
  // Scotland 6Cs opener D: "I demonstrate each of the 6 C's through specific"
  /I demonstrate each of the 6/i,
]

// ─── helpers ──────────────────────────────────────────────────────────────────

// Verb stem → inflection pattern. stem is the minimal base; extras for irregular forms.
function v(stem: string, word: string, suffixes: string[] = ['e', 'es', 'ed', 'ing']): BannedPattern {
  const alts = suffixes.join('|')
  return { pattern: new RegExp(`\\b(${stem}(?:${alts}))\\b`, 'i'), word }
}

// Single word — exact, no inflection (adjective/adverb/noun).
function w(word: string): BannedPattern {
  return { pattern: new RegExp(`\\b(${word})\\b`, 'i'), word }
}

// Multi-word phrase — exact, case-insensitive.
function ph(phrase: string): BannedPattern {
  const esc = phrase.replace(/[-]/g, '\\$&')
  return { pattern: new RegExp(`\\b${esc}\\b`, 'i'), word: phrase }
}

// ─── patterns ─────────────────────────────────────────────────────────────────

const BANNED_PATTERNS: BannedPattern[] = [

  // ── Verb stems (catch all common inflections) ──────────────────────────────
  v('demonstrat',   'demonstrate'),                        // demonstrate/s/ed/ing
  v('ensur',        'ensure'),                             // ensure/s/ed/ing
  v('utilis',       'utilise'),                            // utilise/s/d/ing
  v('utiliz',       'utilise'),                            // American spelling
  v('encompass',    'encompass',  ['es', 'ed', 'ing']),    // encompasses/ed/ing
  v('facilitat',    'facilitate'),
  v('enhanc',       'enhance'),
  v('maintain',     'maintain',   ['s', 'ed', 'ing']),     // no stem change
  v('implement',    'implement',  ['s', 'ed', 'ing']),
  v('foster',       'foster',     ['s', 'ed', 'ing']),
  v('leverag',      'leverage'),
  v('cultivat',     'cultivate'),
  v('streamlin',    'streamline'),
  v('liais',        'liaise'),
  v('collaborat',   'collaborate', ['e', 'es', 'ed', 'ing', 'ion', 'ions', 'ive', 'ively']),
  v('optimi',       'optimise',   ['se', 'ses', 'sed', 'sing', 'ze', 'zes', 'zed', 'zing']),
  v('mitigat',      'mitigate'),
  v('empower',      'empower',    ['s', 'ed', 'ing', 'ment']),
  { pattern: /\b(uphold(?:s|ing)?|upheld)\b/i,     word: 'uphold' },       // irregular past
  { pattern: /\b(endeavou?r(?:s|ed|ing)?)\b/i,     word: 'endeavour' },    // UK + US spelling
  v('aspir',        'aspire',     ['e', 'es', 'ed', 'ing', 'ation', 'ations']),
  v('shap',         'shape'),                              // shape/shapes/shaped/shaping
  { pattern: /\b(span(?:s|ned|ning)?)\b/i,         word: 'span' },
  { pattern: /\b(reflect(?:s|ed|ing)?)\b/i,        word: 'reflect' },      // when linking values
  v('delv',         'delve'),
  v('unlock',       'unlock',     ['s', 'ed', 'ing']),
  v('unveil',       'unveil',     ['s', 'ed', 'ing']),
  v('elevat',       'elevate'),
  v('nestl',        'nestle'),
  v('blend',        'blend',      ['s', 'ed', 'ing']),

  // ── Adjectives / adverbs (exact form, no inflection) ──────────────────────
  w('robust'),
  w('holistic'),
  w('comprehensive'),
  w('passionate'),
  w('dedicated'),
  w('hardworking'),
  w('grounded'),
  w('seamlessly'),
  w('crucial'),
  w('vital'),
  w('notably'),
  w('moreover'),
  w('furthermore'),
  w('additionally'),
  w('proactive'),
  w('dynamic'),
  w('enthusiastic'),
  w('compassionate'),
  w('paramount'),
  w('pivotal'),
  w('integral'),
  w('imperative'),
  w('adept'),
  w('multifaceted'),
  w('nuanced'),
  w('bespoke'),
  w('tremendously'),
  w('immensely'),
  w('substantially'),
  w('bustling'),
  w('vibrant'),
  w('daunting'),
  w('overarching'),
  w('impactful'),
  w('transformative'),
  w('synergy'),

  // ── Nouns (exact) ─────────────────────────────────────────────────────────
  w('plethora'),
  w('realm'),
  w('tapestry'),
  w('landscape'),

  // ── Multi-word phrases ────────────────────────────────────────────────────
  ph('highly motivated'),
  ph('central to'),
  ph('at all times'),
  ph('in order to'),
  ph('with regard to'),
  ph('in relation to'),
  ph('due to the fact that'),
  ph('going forward'),
  ph('moving forward'),
  ph('touch base'),
  ph('not only'),
  ph('not just'),
  ph('more than just'),
  ph('significantly improved'),
  ph('greatly improved'),
  ph('substantially improved'),
  ph('proven track record'),
  ph('fast-paced environment'),
  ph('attention to detail'),
  ph('team player'),
  ph('think outside the box'),
  ph('results-driven'),
  ph('go above and beyond'),
  ph('invaluable experience'),
  ph('from day one'),
  ph('from the first shift'),
  // Outcome-linking phrases
  ph('This resulted in'),
  ph('This led to'),
  ph('As a result'),
  // First-person banned forms
  ph('I would bring'),
  ph('I would ensure'),
  ph('I would contribute'),
  ph('I would strive'),
  ph('I believe I would'),
  ph('I am confident that'),
  ph('I am deeply committed'),
  ph('I genuinely believe'),
  ph('I truly care'),
]

// ─── sentence splitter ────────────────────────────────────────────────────────

function splitSentences(text: string): string[] {
  const sentences: string[] = []
  for (const line of text.split(/\n+/)) {
    const trimmed = line.trim()
    if (!trimmed) continue
    const parts = trimmed.match(/[^.!?]+[.!?]+(?=\s|$)|[^.!?]+$/g) ?? [trimmed]
    for (const part of parts) {
      const s = part.trim()
      if (s.length > 3) sentences.push(s)
    }
  }
  return sentences
}

// ─── public API ───────────────────────────────────────────────────────────────

export function scanBanned(statement: string): BannedWordHit[] {
  const hits: BannedWordHit[] = []
  const seen = new Set<string>()

  for (const sentence of splitSentences(statement)) {
    if (seen.has(sentence)) continue
    if (OPENER_EXEMPT.some(p => p.test(sentence))) continue

    for (const { pattern, word } of BANNED_PATTERNS) {
      const match = sentence.match(pattern)
      if (match) {
        hits.push({ word, found: match[1] ?? match[0], sentence })
        seen.add(sentence)
        break // one hit per sentence — patcher rewrites the whole sentence
      }
    }
  }

  return hits
}
